image:
  registry: registry.cn-shanghai.aliyuncs.com/kube-shipper
  server:
    repository: shipper-server
    tag: v0.1.0
  pullPolicy: IfNotPresent
imagePullSecrets: []

replicaCount: 1
autoscaling:
  enabled: false

nameOverride: ""
fullnameOverride: ""
namespace: "shipper-system"

server:
  podAnnotations: {}
  podSecurityContext: {}
  # fsGroup: 2000
  securityContext: {}
    # capabilities:
    #   drop:
    #   - ALL
    # readOnlyRootFilesystem: true
    # runAsNonRoot: true
  # runAsUser: 1000
  resources:
    limits:
      cpu: 4
      memory: 4Gi
    requests:
     cpu: 100m
     memory: 128Mi
  nodeSelector: {}
  tolerations: []
  affinity: {}
  envs:
    Identity_Authority: "http://ks-apiserver.kubesphere-system.svc"
    Oci_Registry_Host: "hub.cloud.lingbohome.com"
    Oci_Registry_Username: "" 
    Oci_Registry_Password: ""
    Oci_Registry_Token: ""
    Oci_Registry_Group: "shipper-artifacts"
    Oci_Registry_Credentials: ""  

  service:
    type: ClusterIP
    port: 5000

serviceAccount:
  # Specifies whether a service account should be created
  create: true
  annotations: {}
  # The name of the service account to use.
  # If not set and create is true, a name is generated using the fullname template
  name: "shipper-sa"
