
---
apiVersion: extensions.kubesphere.io/v1alpha1
kind: JSBundle
metadata:
  name: {{ include "ui.fullname" . }}-js-bundle
  namespace: {{ default .Release.Namespace .Values.namespace }}
spec:
  rawFrom:
    url: http://shipper-ui.{{ default .Release.Namespace .Values.namespace }}.svc/dist/shipper-ui/index.js
status:
  state: Available
  link: /dist/shipper-ui/index.js
