apiVersion: v1
kind: Service
metadata:
  name: shipper-ui
  namespace: {{ default .Release.Namespace .Values.namespace }}
  labels:
    {{- include "ui.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP
      name: http
  selector:
    {{- include "ui.selectorLabels" . | nindent 4 }}