apiVersion: apps/v1
kind: Deployment
metadata:
  name: shipper-server
  namespace: {{ default .Release.Namespace .Values.namespace }}
  labels:
    {{- include "server.labels" . | nindent 4 }}
spec:
{{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
{{- end }}
  selector:
    matchLabels:
      {{- include "server.selectorLabels" . | nindent 6 }}
  template:
    metadata:
    {{- with .Values.server.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
      labels:
        {{- include "server.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ .Values.serviceAccount.name }}
      securityContext:
        {{- toYaml .Values.server.podSecurityContext | nindent 8 }}
      containers:
        - name: shipper-server
          securityContext:
            {{- toYaml .Values.server.securityContext | nindent 12 }}
          image: "{{ .Values.image.registry }}/{{ .Values.image.server.repository }}:{{ .Values.image.server.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
            - name: SHIPPER_IDENTITY_AUTHORITY
              value: {{ .Values.server.envs.Identity_Authority | quote }}
            - name: SHIPPER_OCI_REGISTRY_HOST
              value: {{ .Values.server.envs.Oci_Registry_Host | quote }}
            - name: SHIPPER_OCI_REGISTRY_USERNAME
              value: {{ .Values.server.envs.Oci_Registry_Username | quote }}
            - name: SHIPPER_OCI_REGISTRY_PASSWORD
              value: {{ .Values.server.envs.Oci_Registry_Password | quote }}
            - name: SHIPPER_OCI_REGISTRY_TOKEN
              value: {{ .Values.server.envs.Oci_Registry_Token | quote }}
            - name: SHIPPER_OCI_REGISTRY_GROUP
              value: {{ .Values.server.envs.Oci_Registry_Group | quote }}
            - name: SHIPPER_OCI_REGISTRY_CREDENTIALS
              value: {{ .Values.server.envs.Oci_Registry_Credentials | quote }}                                                                                      
          ports:
            - containerPort: 5000
              protocol: TCP
              name: http
            - containerPort: 5001
              protocol: TCP
              name: https   
          readinessProbe:
            httpGet:
              path: /healthz
              port: 5000
            timeoutSeconds: 90
            initialDelaySeconds: 5
            periodSeconds: 40
          livenessProbe:
            httpGet:
              path: /healthz
              port: 5000
            timeoutSeconds: 90
            initialDelaySeconds: 60
            periodSeconds: 120              
          resources:
            {{- toYaml .Values.server.resources | nindent 12 }}
      {{- with .Values.server.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.server.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.server.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
