{{- if .Values.serviceAccount.create -}}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.serviceAccount.name }}
  namespace: {{ default .Release.Namespace .Values.namespace }}
  labels:
    {{- include "extension.labels" . | nindent 4 }}
  {{- with .Values.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: shipper-rbac
  labels:
    {{- include "extension.labels" . | nindent 4 }}
rules:
- apiGroups:
    - ""
  resources:
    - secrets
    - configmaps
    - pods
    - persistentvolumeclaims 
  verbs:
    - "*"  
- apiGroups:
  - ""
  resources:
  - events
  verbs:
  - create
  - patch
- apiGroups:
  - ""
  resources:
  - namespaces
  verbs:
  - create
  - get
  - list
  - update
  - watch
- apiGroups:
    - ""
  resources:
    - podtemplates
  verbs:
    - get
    - list
    - update
    - watch
- verbs:
    - '*'
  apiGroups:
    - 'shipper.lingbohome.com'
  resources:
    - '*' 
- apiGroups:
  - authentication.k8s.io
  resources:
  - tokenreviews
  verbs:
  - create
- apiGroups:
  - authorization.k8s.io
  resources:
  - subjectaccessreviews
  verbs:
  - create     

---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: shipper-rbac
  labels:
    {{- include "extension.labels" . | nindent 4 }}
subjects:
  - kind: ServiceAccount
    name: {{ .Values.serviceAccount.name }}
    namespace: {{ default .Release.Namespace .Values.namespace }}
roleRef:
  kind: ClusterRole
  name: shipper-rbac
  apiGroup: rbac.authorization.k8s.io
{{- end }}
