apiVersion: v1
kind: Service
metadata:
  name: shipper-server
  namespace: {{ default .Release.Namespace .Values.namespace }}
  labels:
    {{- include "server.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - port: 5000
      targetPort: 5000
      protocol: TCP
  selector:
    {{- include "server.selectorLabels" . | nindent 4 }}