{{- if .Values.serviceAccount.create -}}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.serviceAccount.name }}
  namespace: {{ default .Release.Namespace .Values.namespace }}
  labels:
    {{- include "extension.labels" . | nindent 4 }}
  {{- with .Values.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: shipper-rbac
  labels:
    {{- include "extension.labels" . | nindent 4 }}
rules:
- apiGroups:
    - ''
    - 'apps'
    - 'batch'
    - 'app.k8s.io'
    - 'autoscaling'
    - 'rbac.authorization.k8s.io'
  resources:
    - '*'
  verbs:
    - '*'       
- apiGroups:
  - ""
  resources:
  - events
  verbs:
  - create
  - update
  - patch
- verbs:
    - '*'
  apiGroups:
    - 'shipper.lingbohome.com'
  resources:
    - '*' 
- apiGroups:
  - authentication.k8s.io
  resources:
  - tokenreviews
  verbs:
  - create
- apiGroups:
  - authorization.k8s.io
  resources:
  - subjectaccessreviews
  verbs:
  - create
- apiGroups:
  - 'tekton.dev'
  resources:
  - '*'
  verbs:
  - '*'
- nonResourceURLs:
  - "/metrics"
  verbs:
  - get     

---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: shipper-rbac
  labels:
    {{- include "extension.labels" . | nindent 4 }}
subjects:
  - kind: ServiceAccount
    name: {{ .Values.serviceAccount.name }}
    namespace: {{ default .Release.Namespace .Values.namespace }}
roleRef:
  kind: ClusterRole
  name: shipper-rbac
  apiGroup: rbac.authorization.k8s.io

---
kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: shipper-rbac
  namespace: {{ default .Release.Namespace .Values.namespace }}
  labels:
    {{- include "extension.labels" . | nindent 4 }}
rules:
  - verbs:
      - '*'
    apiGroups:
      - ''
      - 'apps'
      - 'batch'
      - 'app.k8s.io'
      - 'autoscaling'
    resources:
      - '*'
  - apiGroups:
    - coordination.k8s.io
    resources:
    - leases
    verbs:
    - get
    - list
    - watch
    - create
    - update
    - patch
    - delete
  - apiGroups:
    - ""
    resources:
    - events
    verbs:
    - create
    - patch    

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: shipper-rbac
  namespace: {{ default .Release.Namespace .Values.namespace }}
  labels:
    {{- include "extension.labels" . | nindent 4 }}
subjects:
  - kind: ServiceAccount
    name: {{ .Values.serviceAccount.name }}
    namespace: {{ default .Release.Namespace .Values.namespace }}
roleRef:
  kind: Role
  name: shipper-rbac
  apiGroup: rbac.authorization.k8s.io

{{- end }}


