
global:
  namespace: "shipper-system"

image:
  registry: registry.cn-shanghai.aliyuncs.com/kube-shipper
  controller:
    repository: tektoncd-pipeline-controller
    tag: v0.54.2
  event:
    repository: tektoncd-pipeline-events
    tag: v0.54.0
  webhook:
    repository: tektoncd-pipeline-webhook
    tag: v0.54.0
  resolvers:
    repository: tektoncd-pipeline-resolvers
    tag: v0.54.2    
  entrypoint:
    repository: tektoncd-pipeline-entrypoint
    tag: v0.54.0
  nop:
    repository: tektoncd-pipeline-nop
    tag: v0.54.0
  sidecarlogresults:
    repository: tektoncd-pipeline-sidecarlogresults
    tag: v0.54.0
  workingdirinit:
    repository: tektoncd-pipeline-workingdirinit
    tag: v0.54.0
  chainguardBusybox:
    repository: chainguard-busybox
    tag: latest
  powershell:
    repository: powershell
    tag: nanoserver
  kubectl:
    repository: kubectl
    tag: v1.27.4                                 
  pullPolicy: IfNotPresent

imagePullSecrets: []

nameOverride: ""
fullnameOverride: ""

crds:
  disableUpgrade: false



